services:
  test-postgres:
    image: 'postgres:16'
    container_name: test-postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    mem_limit: 4g
    cpus: 2.0
    volumes:
      - test-postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    mem_limit: 4g
    cpus: 2.0

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
    mem_limit: 4g
    cpus: 2.0

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    mem_limit: 8g
    cpus: 4.0

  spring-app:
    image: my-spring-app
    ports:
      - "8080:8080"
    mem_limit: 4g
    cpus: 2.0
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://test-postgres:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - test-postgres

volumes:
  test-postgres-data:
  grafana-data:
  influxdb-data:
