### 금칙어 등록1
POST {{host}}/terms/register
Content-Type: application/json

{
  "terms": [
    "fuck",
    "shit",
    "bastard",
    "asshole",
    "bitch",
    "son of a bitch",
    "dumbass",
    "jackass",
    "dipshit",
    "crap",
    "piss off",
    "screw you",
    "bloody hell",
    "goddamn",
    "hell",
    "motherfucker",
    "prick",
    "twat",
    "wanker",
    "moron",
    "jerk",
    "idiot",
    "imbecile",
    "retard",
    "loser",
    "douchebag",
    "dickhead",
    "cockhead",
    "shithead",
    "pussy",
    "slut",
    "whore",
    "scumbag",
    "faggot",
    "cunt",
    "ballsack",
    "sack of shit",
    "dumb fuck",
    "useless piece of shit",
    "go to hell",
    "eat shit",
    "kiss my ass",
    "shut the fuck up",
    "stupid motherfucker",
    "piece of crap",
    "lazy fuck",
    "ugly fuck",
    "fat fuck",
    "shitface",
    "shit stain",
    "craphead",
    "son of a whore",
    "goddamn idiot",
    "worthless fuck",
    "bitchass",
    "crybaby",
    "nutjob",
    "psycho",
    "dumb bitch",
    "crazy bastard",
    "shitshow",
    "clusterfuck",
    "sick fuck",
    "dirty whore",
    "lying bastard",
    "suck my dick",
    "chode",
    "jerkwad",
    "airhead",
    "twit",
    "smeghead",
    "ballbuster",
    "drunk fuck",
    "scrawny little shit",
    "shitbag",
    "dickwad",
    "arsehole",
    "tosser",
    "waste of space",
    "crying bitch",
    "drama queen",
    "useless asshole",
    "cowardly prick",
    "numbskull",
    "asswipe",
    "cocksmoker",
    "fucking idiot",
    "shit eater",
    "pain in the ass",
    "blowhard",
    "ball-licker",
    "prissy bitch",
    "hypocrite",
    "bitchy",
    "shit for brains",
    "full of shit",
    "backstabbing bitch",
    "씨발",
    "ㅅㅂ",
    "시발",
    "씨팔",
    "ㅆㅂ",
    "좆",
    "좃",
    "개새끼",
    "개자식",
    "미친놈",
    "미친년",
    "병신",
    "븅신",
    "병신새끼",
    "개병신",
    "씹새끼",
    "씨발년",
    "지랄",
    "지랄하네",
    "존나",
    "좆밥",
    "좆같네",
    "씨발놈",
    "씨발새끼",
    "씹할",
    "닥쳐",
    "꺼져",
    "뒤질래",
    "뒤져라",
    "엿먹어",
    "엿이나 처먹어",
    "좆까",
    "개좆",
    "개지랄",
    "노답",
    "정신병자",
    "돌아이",
    "똘아이",
    "틀딱",
    "틀딱충",
    "좆만한",
    "좆도 모르는",
    "좆병신",
    "좆같은",
    "개같은",
    "걸레같은",
    "걸레년",
    "창녀",
    "야동충",
    "변태새끼",
    "개씹새끼",
    "더러운새끼",
    "씨부럴",
    "씨부랄",
    "병맛",
    "빠가사리",
    "씹덕",
    "찐따",
    "빻은년",
    "꼴페미",
    "구라쟁이",
    "버러지",
    "좆빨아",
    "씹창",
    "씹창년",
    "빨갱이",
    "짱깨",
    "조센징",
    "멍청한 새끼",
    "썅년",
    "썅놈",
    "개버러지",
    "배때기 갈라",
    "아가리 닥쳐",
    "fuckin",
    "slutty",
    "foolish",
    "idiotic",
    "punk",
    "crappy",
    "shithead",
    "foolish bitch",
    "lazy idiot",
    "silly jackass",
    "stupid prick",
    "worthless moron",
    "dumb idiot",
    "pathetic loser",
    "stupid bitch"
  ]
}

> {%
    client.test("대량 금칙어 등록 테스트", () => {
        client.assert(response.status === 200, "Status must be 200");
    });
%}

### 금칙어 등록2
POST {{host}}/terms/register
Content-Type: application/json

{
  "terms": [
    "asshat",
    "badass",
    "douche",
    "moron",
    "dick",
    "shitbag",
    "cockmuncher",
    "balllicker",
    "assclown",
    "cocksucker",
    "fag",
    "loser",
    "douchecanoe",
    "twatface",
    "shitbird",
    "cumface",
    "buttplug",
    "slutbag",
    "turd",
    "prickface",
    "dickwad",
    "pisshole",
    "bastardfuck",
    "cockhead",
    "fuckery",
    "fuckoff",
    "shitter",
    "fagbag",
    "whorebag",
    "idiotass",
    "bastardisation",
    "assrider",
    "fucktard",
    "twathead",
    "fatass",
    "bitchtits",
    "asswipe",
    "twatwaffle",
    "bitchfucker",
    "analbeads",
    "cockroach",
    "shitstain",
    "cuntface",
    "cockblock",
    "fuckbuckets",
    "shitfaced",
    "twatsicle",
    "blowme",
    "prickwhore",
    "dickheads",
    "pissass",
    "dickheadfuck",
    "shitstorm",
    "fuckpuppy",
    "skumbag",
    "dickfist",
    "asshat",
    "crackwhore",
    "assmunch",
    "moronscum",
    "blowjobber",
    "cumdumpster",
    "fuckingidiot",
    "shitlicker",
    "pisspants",
    "dicknugget",
    "cockwobble",
    "buttcheeks",
    "cuntface",
    "pissypants",
    "buttfucker",
    "whoremonkey",
    "sodomizer",
    "buttpirate",
    "assfucker",
    "dildoking",
    "sexslut",
    "twobitwhore",
    "jackasshole",
    "clitlicker",
    "ballsucker",
    "cumslut",
    "shitfuck",
    "cockwhore",
    "asspussy",
    "freakface",
    "butthole",
    "fuckyourself",
    "cumrag",
    "twathole",
    "fuckjuice",
    "spunkbag",
    "pussywhip",
    "fucktastic",
    "cockslave",
    "dicknibble",
    "cockmunch",
    "jizzbag",
    "pisshead",
    "whorish",
    "bitchslut",
    "buttplugger",
    "dickhole",
    "ballsackhole",
    "cockswallow",
    "titsucker",
    "cuntbag",
    "assgoblin",
    "fagboy",
    "buttfuck",
    "cockheadfuck",
    "fuckasshole",
    "cuntlicker",
    "pisscup",
    "asslover",
    "whorefucker",
    "asswhore",
    "dicksucker",
    "slutwhore",
    "assfag",
    "cockpiece",
    "bastardass",
    "pisscock",
    "shitwhore",
    "cockrag",
    "twatschasm",
    "asskisser",
    "dumbfuck",
    "pricktease",
    "whoremonger",
    "slutbucket",
    "cumshitter",
    "assball",
    "fuckingbastard",
    "pisswhore",
    "cocknip",
    "assholer",
    "fuckerface",
    "buttdick",
    "cockgrinder",
    "jizzwhore",
    "cumass",
    "skankwhore",
    "shitprick",
    "pussydick",
    "slutfuck",
    "cockstain",
    "twatfucker",
    "buttnugget",
    "dickbitch",
    "suckmyleg",
    "suckmeoff",
    "prickfuck",
    "cockface",
    "twatheadfuck",
    "shitnugget",
    "skunkass",
    "cumthroat",
    "dumbasshole",
    "fuckpussy",
    "cocktailwhore",
    "clitfucker",
    "asswipefuck",
    "twatdog",
    "cockwhorehole",
    "fuckingwhore",
    "dicklick",
    "bastardfuck",
    "shitlickerfuck",
    "twatnugget",
    "whorebagging",
    "fagbucket",
    "cocksniffer",
    "fuckasshole",
    "pisslicker",
    "shitspout",
    "cockhorse",
    "jizzgoblin",
    "pissfuck",
    "twatball",
    "slutshitter",
    "cuntwhore",
    "bastardcunt",
    "fuckhorse",
    "prickface",
    "turdwhore",
    "sluthead",
    "twatmunch",
    "cockragface",
    "asskissingfucker",
    "jizzslut",
    "twatgoblin",
    "cockblow",
    "dickrag",
    "whorefuck",
    "shitheadface",
    "buttcrack",
    "twatbag",
    "asslick",
    "cocknugget",
    "assholefuck",
    "fuckbrains"
  ]
}


> {%
    client.test("대량 금칙어 등록 테스트", () => {
        client.assert(response.status === 200, "Status must be 200");
    });
%}

### 금칙어 등록3
POST {{host}}/terms/register
Content-Type: application/json

{
  "terms": [
    "씨팔",
    "씨발새끼",
    "좆같은",
    "좆같네",
    "좆밥",
    "좆병신",
    "병신새끼",
    "병신같은",
    "좆꼴",
    "좆나",
    "미친년",
    "미친놈",
    "빻은년",
    "빻은놈",
    "똘아이",
    "돌아이",
    "어리석은 놈",
    "개새끼",
    "개새끼야",
    "개자식",
    "개병신",
    "개병신새끼",
    "개찌라시",
    "개빡대가리",
    "개씨발",
    "좆병신새끼",
    "좆물",
    "좆년",
    "찌질이",
    "씹새끼",
    "씨발년",
    "좆까",
    "좆을까",
    "좆밥새끼",
    "지랄",
    "지랄하네",
    "죽을래",
    "뒤져라",
    "뒤질래",
    "시발새끼",
    "시발놈",
    "시발년",
    "씹새끼년",
    "씹할",
    "병신새끼",
    "개좆",
    "좆잡자",
    "좆팔",
    "좆썰",
    "좆놈",
    "꺼져",
    "꺼져라",
    "엿먹어",
    "엿이나 처먹어",
    "개좆같은",
    "개지랄",
    "좆같이",
    "염병",
    "짱깨",
    "미친새끼",
    "미친개",
    "엿같은",
    "씨발넘",
    "뻐꾸기",
    "정신병자",
    "깨진놈",
    "몽둥이질",
    "병신같이",
    "개같은년",
    "좆같은놈",
    "시발벌레",
    "거지새끼",
    "시발새끼같은",
    "시발새끼들",
    "신새끼",
    "잘못된 새끼",
    "걸레년",
    "잡년",
    "창녀",
    "더러운년",
    "좆남",
    "시발남",
    "좆씹어",
    "애비년",
    "애비새끼",
    "쌍년",
    "이쁜년",
    "미친새끼들",
    "똥년",
    "씹창년",
    "노답년",
    "또라이",
    "또라이년",
    "늙은년",
    "헛소리",
    "헛소리새끼",
    "좆망",
    "바보년",
    "짱구새끼",
    "팔짱새끼",
    "좆치",
    "씹탱",
    "씹팔",
    "씹새",
    "디져라",
    "빠가사리",
    "자식새끼",
    "시발어머니",
    "개풀밭에",
    "씨발놈",
    "죽은새끼",
    "돌아이새끼",
    "파렴치한",
    "대가리깨진놈",
    "박살낸놈",
    "엿이나 처먹어라",
    "강간놈",
    "조롱하고",
    "진상새끼",
    "비정상새끼",
    "좆녀",
    "깜빡이",
    "똑바로해라",
    "쌈박한",
    "막가파",
    "경상도년",
    "바닥새끼",
    "짜증나",
    "피버",
    "짜증내지마",
    "죽을래",
    "식충이",
    "돈빨아먹고",
    "돈벌레",
    "닭살",
    "지랄같은",
    "거지새끼들",
    "고자새끼",
    "사팔이",
    "십팔자",
    "쫌살",
    "짓거리지마",
    "욕하지마",
    "썩은놈",
    "폐물같은",
    "불쌍한놈",
    "허접년",
    "깨진머리",
    "자기애",
    "얄미운년",
    "살아있는시체",
    "겁쟁이",
    "겁박하는놈",
    "사라져",
    "거지새끼",
    "좆문",
    "뭉개기",
    "새끼",
    "무시하지마",
    "갈팡질팡",
    "개짓거리",
    "혼자서",
    "꿀리지마",
    "찌질한",
    "좆병",
    "좆크다",
    "쓰레기통",
    "전빨",
    "새끼굴리기",
    "욕먹는놈",
    "싸가이",
    "개떡밥",
    "피지배",
    "걸레털기",
    "빡세다",
    "작은것",
    "살아있는놈",
    "그냥 버려라",
    "똥벌레",
    "쥐새끼",
    "위험한놈",
    "헛짓거리",
    "씹헛소리",
    "빡칠정도",
    "새벽불닭",
    "섹스토이",
    "얼굴없음",
    "쩔어",
    "피지배자",
    "타라쳐",
    "비하새끼",
    "기름지다",
    "서툴렁",
    "골때리는놈",
    "대리운전",
    "부대쑈",
    "망가진놈",
    "망할놈",
    "옛날놈",
    "제멋대로",
    "말도안돼",
    "개백수",
    "세상물정",
    "해지기전",
    "잡종같은",
    "서민같은",
    "얘기를많이해",
    "대화나누지마",
    "시끄럽다",
    "운전이나해",
    "무식한",
    "난잡한놈",
    "답답한놈",
    "내탓이아닌데",
    "개엑스",
    "시체랑놀다",
    "씁쓰레기",
    "알빠아냐",
    "쩔음기",
    "오만한",
    "죽고싶지않다"
  ]
}

> {%
    client.test("대량 금칙어 등록 테스트", () => {
        client.assert(response.status === 200, "Status must be 200");
    });
%}


### 금칙어 등록4
POST {{host}}/terms/register
Content-Type: application/json

{
  "terms": [
    "노답",
    "찐따",
    "짱깨",
    "시발놈",
    "좆밥",
    "좆같은",
    "미친놈",
    "미친년",
    "병신",
    "븅신",
    "개병신",
    "똘아이",
    "개새끼",
    "좆병신",
    "죽을래",
    "존나",
    "좆같네",
    "시발",
    "씨발",
    "좆까",
    "씹새끼",
    "엿먹어",
    "뒤져",
    "뒤져라",
    "좆나",
    "씨팔",
    "좆밥새끼",
    "씨발년",
    "씹새끼년",
    "씨팔년",
    "어처구니없다",
    "좆먹",
    "좆빨",
    "신발자국",
    "짓거리",
    "디져라",
    "좆쳐",
    "개빡",
    "개찌랄",
    "겁쟁이",
    "씨발새끼",
    "싸가지",
    "한심하다",
    "미친놈들",
    "무시하지마",
    "너미친새끼",
    "정신병자",
    "병신같은",
    "개빡대가리",
    "인간쓰레기",
    "좆벌레",
    "죽은새끼",
    "헛소리",
    "부모새끼",
    "창녀",
    "엿이나 처먹어",
    "헛짓거리",
    "개자식",
    "부탁하지마",
    "징징대지마",
    "심심해서짖어",
    "맘대로해라",
    "탱크새끼",
    "죽을줄알고",
    "시발끼",
    "배때기",
    "앉아봐",
    "넌할만큼했다",
    "무리하지마",
    "조용히해",
    "단한사람도없다",
    "빨리죽어라",
    "일하지마",
    "천박한새끼",
    "미친개",
    "넌잘할수있다",
    "미친어린이",
    "멍청한놈",
    "쓰레기통",
    "씨발년새끼",
    "좆빠는년",
    "새끼가",
    "때려죽여",
    "시발병신",
    "지랄해",
    "마음대로살아",
    "멍청한년",
    "존나빡쳐",
    "존나기분나빠",
    "미친놈아",
    "미친년",
    "존못",
    "더럽다",
    "더러운년",
    "성격파탄자",
    "짜증난다",
    "좆크네",
    "죽으라고해",
    "좆폭",
    "고구마먹어",
    "병신보지",
    "병신새끼",
    "짜증낸다",
    "꺼져라",
    "시발새끼",
    "에이구",
    "어쩌라고",
    "아가리닥쳐",
    "씨발걸레",
    "눈물흘려라",
    "알았어",
    "잡년",
    "너같은새끼",
    "시발존나",
    "좆탱",
    "새끼그만",
    "미친새끼들",
    "병이던거같아",
    "몸짱과팔짱",
    "쌍욕",
    "쓰레기형",
    "자살해",
    "할매새끼",
    "할아버지",
    "할머니",
    "좀비년",
    "좀비놈",
    "좀비녀",
    "알바하자",
    "징징대다",
    "빨갱이새끼",
    "독재새끼",
    "미친놈들",
    "혐오증",
    "싫어죽겠다",
    "입뻥",
    "불쌍한애들",
    "참견좀하지마",
    "귀찮다",
    "짖어",
    "적당히",
    "패드립",
    "발정난년",
    "개운해",
    "잘난척",
    "가져가라",
    "똑바로해",
    "병신같은놈",
    "짬뽕먹자",
    "수고해",
    "네가먼저잘해",
    "고독하게살자",
    "열등감",
    "꼬리꼬리한",
    "사람도아닌놈",
    "인간미비",
    "닭살을올려",
    "부모와자식",
    "바퀴벌레새끼",
    "똥개",
    "패드립",
    "술먹으러가자",
    "거지같은놈",
    "최악",
    "죽은자가되기",
    "살아있는자처럼",
    "단하나라도",
    "새끼구리",
    "쩝쩝",
    "천상병신",
    "배짱이죽은놈",
    "이상해진놈",
    "보지말고살자",
    "손톱닦이",
    "대머리",
    "형광놈",
    "형광녀",
    "거지애비",
    "징벌나온놈",
    "폭력배새끼",
    "이딴게병자",
    "길치어린이",
    "시끄럽다",
    "짖기만해라",
    "덮어놔",
    "거부반응",
    "박살내버려",
    "꺼져",
    "빨갛게",
    "핸드폰중독",
    "짖어대다",
    "입새는녀",
    "쟤넘버원",
    "변태쓰레기",
    "좆빠진년",
    "입벌려",
    "죽은걸음새끼",
    "죽어서가자"
  ]
}


> {%
    client.test("대량 금칙어 등록 테스트", () => {
        client.assert(response.status === 200, "Status must be 200");
    });
%}