# GET
POST {{host}}/sample/hello?name=HOOHO&query=123
Content-Type: application/json

{
  "name": "HddOHO",
  "query": "1dd23"
}


###
# GET
POST {{host}}/sample/slow
Content-Type: application/json

{
  "name": "HddOHO",
  "query": "1dd23"
}

###
# GET
POST {{host}}/sample/error
Content-Type: application/json

{
  "name": "HddOHO",
  "query": "1dd23"
}


