CREATE TABLE IF NOT EXISTS forbidden_term
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term        VARCHAR(255) NOT NULL,
    category    VARCHAR(255),
    created_by  VARCHAR(255) NOT NULL DEFAULT 'anonymous',
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    modified_by VARCHAR(255) NOT NULL DEFAULT 'anonymous',
    modified_at TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_forbidden_term_exact
    ON forbidden_term (term);